=== Alejandroluna05/Lenguaje/LM/ud3/xml/ejerciciosxml/ejercicio5.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="dni" type="xs:string"/>
                            <xs:element name="comentario" type="xs:string"/>
                            <xs:element name="fecha-nacimiento" type="xs:date" minOccurs="0"/>
                            <xs:element name="forma-pago" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="numero-tarjeta" type="xs:string" minOccurs="0"/>
                                        <xs:element name="cuenta-bancaria" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="tipo" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Alejandroluna05/Lenguaje/LM/ud3/xml/ejerciciosxml/ejercicio5.xml
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicio5.xsd">
    <persona>
        <nombre>Juan PÃ©rez</nombre>
        <dni>12345678A</dni>
        <comentario>Cliente VIP</comentario>
        <fecha-nacimiento>1985-06-24</fecha-nacimiento>
        <forma-pago tipo="tarjeta">
            <numero-tarjeta>1234567890123456</numero-tarjeta>
        </forma-pago>
    </persona>
</personas>
